import type { DashboardTransaction } from "@/components/dashboard/DashboardTransactions";

export const demoTransactions: DashboardTransaction[] = [
  {
    id: "1",
    type: "income",
    amount: 350,
    category: "Vendas",
    paymentMethod: "Pix",
    description: "Venda de produtos",
    date: "Hoje, 14:32",
  },
  {
    id: "2",
    type: "expense",
    amount: 120,
    category: "Fornecedores",
    paymentMethod: "Pix",
    description: "Compra de materiais",
    date: "Hoje, 12:18",
  },
  {
    id: "3",
    type: "income",
    amount: 480,
    category: "Vendas",
    paymentMethod: "Cartão",
    description: "Venda de produtos",
    date: "Hoje, 09:47",
  },
  {
    id: "4",
    type: "expense",
    amount: 45,
    category: "Transporte",
    paymentMethod: "Pix",
    description: "Combustível",
    date: "Ontem, 17:20",
  },
  {
    id: "5",
    type: "income",
    amount: 720,
    category: "Serviços",
    paymentMethod: "Pix",
    description: "Projeto de identidade visual",
    date: "Ontem, 15:10",
  },
  {
    id: "6",
    type: "expense",
    amount: 180,
    category: "Operacional",
    paymentMethod: "Pix",
    description: "Assinaturas e ferramentas",
    date: "18 Ago, 18:40",
  },
];
